app/models.py
from datetime import datetime
from sqlalchemy.orm import backref
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from . import db


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


class User(UserMixin, db.Model):
    __tablename__='users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255))
    pass_secure  = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')
    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)
    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)
        
    def __repr__(self):
        return f'User {self.username}'

class Session(db.Model):
    __tablename__='sessions'
    id = db.Column(db.Integer, primary_key=True)
    tarehe = db.Column(db.Date())
    email = db.Column(db.String(255))
    service=db.Column(db.String(255))
    status= db.Column(db.String(255))

class Cancel(db.Model):
    __tablename__='del'
    id = db.Column(db.Integer, primary_key=True)
    tarehe = db.Column(db.Date())
    email = db.Column(db.String(255))
    service=db.Column(db.String(255))
    status= db.Column(db.String(255))


class Contact(db.Model):
    __tablename__='feedback'
    id = db.Column(db.Integer, primary_key=True)
    name= db.Column(db.String(255))
    email = db.Column(db.String(255))
    message=db.Column(db.String(255))
    

app/main/forms.py
from datetime import date
from flask_wtf import FlaskForm
from wtforms import DateField,SelectField,SubmitField,StringField
from flask_datepicker import datepicker
from wtforms.fields.html5 import DateField
from wtforms.fields.simple import TextAreaField
from wtforms.validators import ValidationError, Required

class BookForm(FlaskForm):
    service=SelectField('Select Service',choices=[('',''),("Salon","Salon"),("Barbershop","Barbershop")],validators=[Required()])
    tarehe=DateField('Date')
    email=StringField('Email') 
    submit=SubmitField('Book')
    

class FeedbackForm(FlaskForm):
    
    name=StringField('Full name')
    email=StringField('Email') 
    message=TextAreaField('Message')
    submit=SubmitField('Leave a feedbck')

app/__init__.py
from flask import Flask
from config import config_options
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

bootstrap= Bootstrap()
db=SQLAlchemy()


login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
from flask_mail import Mail

mail = Mail()
def create_app(config_name):
    app= Flask(__name__)
    app.config.from_object(config_options[config_name])
    
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
    #
    from .auth import  auth as auth_blueprint
    app.register_blueprint(auth_blueprint)
    from .main import  main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint
main= Blueprint('main',__name__)

from . import views,forms

app/main/views.py
from datetime import date
from flask import render_template, url_for, redirect, abort
from flask.globals import session
from flask.helpers import flash
from ..models import Cancel, Contact, Session
from . import main
from .forms import BookForm,FeedbackForm
from .. import db
from flask_login import login_required,current_user


@main.route('/')
def index():
    items= [
        {'id': 1,  'service': 'Black hair', 'price': 'Ksh.500'},
        {'id': 2,  'service': 'Box', 'price': 'Ksh.950'},
        {'id': 3,  'service': 'Beards', 'price': 'Ksh. 700'},
        {'id': 4,  'service': 'Dreadlocks', 'price': 'Ksh. 550'},
        {'id': 5,  'service': 'Obama', 'price': 'Ksh. 650'},
        {'id': 6,  'service': 'Facial hair', 'price': 'Ksh. 750'},
        {'id': 7,  'service': 'Buzzcut', 'price': 'Ksh. 800'},
        {'id': 8,  'service': 'Fade', 'price': 'Ksh. 1200'}
    ]
    return render_template('homepage.html', items=items)

@main.route('/book',methods=['POST','GET'])
@login_required
def book():
    title='Book'
    form= BookForm()
    if form.validate_on_submit():
        tarehe=form.tarehe.data
        service=form.service.data
        email=form.email.data
        booking=Session(tarehe=tarehe, service=service, email=email, status='Booked')  
        db.session.add(booking)
        db.session.commit()
        return redirect(url_for('main.homepage'))
    return render_template('book.html',title=title,form=form)

@main.route('/delete_post/<int:id>',methods=['POST','GET'])
@login_required
def del_posts(id):
   com_to_del=Session.query.filter_by(id=id).first()
   com_to=Cancel(tarehe=com_to_del.tarehe, service=com_to_del.service, email=com_to_del.email, status='Freed')
   db.session.add(com_to)
   db.session.commit()

   db.session.delete(com_to_del)
   db.session.commit()
   flash('You have successfully cancelled a booked service', 'success')
   return redirect(url_for('main.homepage'))

@main.route('/edit_post/<int:id>',methods=['POST','GET'])
@login_required
def edit_session(id):
    art=Cancel.query.filter_by(id=id).first()
    print(art)
    if art is None:
        abort(404)
    if art.status=='Booked':
        art=Cancel.query.filter_by(id=id).first()
        com_to=Session(tarehe=art.tarehe, service=art.service, email=art.email, status='Freed')
        db.session.add(com_to)
        db.session.commit()
        db.session.delete(art)
        db.session.commit()
        return redirect(url_for('main.homepage') )
    else:
        art=Cancel.query.filter_by(id=id).first()
        com_to=Session(tarehe=art.tarehe, service=art.service, email=current_user.email, status='Booked')
        db.session.add(com_to)
        db.session.commit()
        db.session.delete(art)
        db.session.commit()
        return redirect(url_for('main.homepage') )
    return redirect(url_for('main.index'))

@main.route('/edit_available/<int:id>',methods=['POST','GET'])
@login_required
def edit_available(id):
    art=Session.query.filter_by(id=id).first()
    print(art)
    if art is None:
        abort(404)
    
    art=Session.query.filter_by(id=id).first()
    com_to=Session(tarehe=art.tarehe, service=art.service, email=current_user.email, status='Booked')
    db.session.add(com_to)
    db.session.commit()
    return redirect(url_for('main.homepage') )

@main.route('/homepage')
@login_required
def homepage():
    title='Home'
    sessions=Session.query.filter_by(status="Booked").all()
    available=Session.query.filter_by(status="Freed").all()

    session=Cancel.query.all()
    print(sessions)
    return render_template('index.html',title=title, session=sessions, sessions=session, available=available)

@main.route('/contact', methods=['GET','POST'])
def contact():
    form= FeedbackForm()
    if form.validate_on_submit():
        name=form.name.data
        email=form.email.data
        message=form.message.data
        feedback=Contact(name=name, message=message, email=email)  
        db.session.add(feedback)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('contact.html',form=form)

app/templates/base.html
{%extends 'bootstrap/base.html'%}
    {% block styles %} {{super()}}
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
     {% endblock %} 
     {%block navbar%} {%
    include 'navbar.html' %}
    {%endblock%}
   

app/templates/book.html
{% extends 'base.html' %}


{% import "bootstrap/wtf.html" as wtf %}

<title>{{title}}</title>
{% block content %}
<div class="container">
    <div class="col-md-7">
        <div class="card">
            
            {{wtf.quick_form(form)}}
        </div>
    </div>
</div>

{% endblock %}

app/templates/contact.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}
{% block content%}
    <div class="card" style="width: 50rem; margin-left: 30%;">
        <img src="{{url_for('static', filename='images/contact.jpg')}}" alt="">
        <div class="card-body">
          <h2 class="card-title">Feedback form</h2>
          {{wtf.quick_form(form, button_map={'submit':'success'})}}
          <br>
        </div>
        <img src="{{url_for('static', filename='images/icons.png')}}" alt="">
      </div>
      
{% endblock%}

app/templates/homepage.html
{% extends 'base.html' %}

{% block title %}
    Home Page
{% endblock %}

{%block content%}

<body class="container-fluid" style="font-size: large; background-color: #c7c4c4;">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <div style="font-size: 30px; margin-top:20px; text-align: center;">
            <h3>Your number 1 spa services spot </h3>
        </div>
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
            <div class="item active">
                <img style="height: 300px; width: 100%" src="{{url_for('static',filename='images/salon1.jpeg')}}" alt="salon1">
                <div class="carousel-caption">
                    <div class="" style="font-size: 20px; margin-top:40px; text-align: center;">
                        <cite title="Source Title"> </cite>
                    </div>
                </div>
            </div>

            <div class="item">
                <img style="height: 300px; width: 100%" src="{{url_for('static',filename='images/salon2.jpg')}}" alt="salon2">
                <div class="carousel-caption">
                    <div class="" style="font-size: 20px; margin-top:40px; text-align: center;">
                        
                        <cite title="Source Title"> </cite>
                    </div>
                </div>
            </div>

            <div class="item">
                <img style="height: 300px; width: 100%;" src="{{url_for('static',filename='images/salon3.jpeg')}}" alt="salon3">
                <div class="carousel-caption">
                    <div class="" style="font-size: 20px; margin-top:40px; text-align: center;opacity: 0.4;">
                        
                        <cite title="Source Title"> </cite>
                    </div>
                </div>
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div style="font-size: 20px; margin-top:40px; text-align: center; box-sizing: border-box;">
        <h1>Services</h1>
    </div>
    <h3>Men</h3>
    <div class="container"> 
       
        <table class="table table-hoover table-success">
            <thread>
                <tr>
                    <th scope="col">ID</th>
                    <!-- <th scope="col">Image</th> -->
                    <th scope="col">Service</th>
                    <th scope="col">Price</th>
                    <th scope="col">Action</th>
                </tr>
            </thread>
            <tbody>
                {% for item in items %}
                <tr>
                    <td>{{ item.id }}</td>
                    <!-- <td>{{ item.image }}</td> -->
                    <td>{{ item.service }}</td>
                    <td>{{ item.price }}</td>
                    <!-- <td>{{ item.Action }}</td> -->
                    
                    <td>
                        <a href="{{url_for('main.homepage')}}"><button class="btn btn-outline btn-info">Book Service</button></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
    <h3>Ladies</h3>
    <div class="container "> 
        
        <table class="table table-hoover table-success">
            <thread>
                <tr>
                    <th scope="col">ID</th>
                    <!-- <th scope="col">Image</th> -->
                    <th scope="col">Service</th>
                    <th scope="col">Price</th>
                    <th scope="col">Action</th>
                </tr>
            </thread>
            <tbody>
                {% for item in items %}
                <tr>
                    <td>{{ item.id }}</td>
                    <!-- <td>{{ item.image }}</td> -->
                    <td>{{ item.service }}</td>
                    <td>{{ item.price }}</td>
                    <!-- <td>{{ item.Action }}</td> -->
                    
                    <td>
                        <a href="{{url_for('main.homepage')}}"><button class="btn btn-outline btn-info">Book Service</button></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
    <div style="font-size: 80px; margin-top:40px; text-align: center; box-sizing: border-box;">
        <a href="/contact" class=" btn btn-primary btn-lg active btn-outline-success" role="button" arial-pressed="true"style="font-size: 40px; margin-bottom:60px; ">Contact Us</a> 
    </div>
       

    

    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.7.0/moment.min.js" type="text/javascript"></script>
</body>

{%endblock%}

app/templates/index.html
{% extends 'base.html' %}

{%block styles%}
{{ super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}">
{%endblock%}
{%if title%}

<title>{{title}}</title>
{%else%}
<title>Processing</title>
{%endif%}
{%block content%}

<div class="container-fluid">
    
       <div class="row">
        <div class="col-md-8" style="height:350px;width:60%;min-width:1000px;border:1px ">
            <img src="https://static.businessworld.in/article/article_extra_large_image/1589448910_mKTyMh_salon_mangalore4.jpg" alt="" style="height:90%;width:100%">
        </div>
        <!-- <div class="col-md-3" style="height:300px;width:39%;border:1px solid black"></div> -->
       </div>
    

</div>
<div class="container-fluid">
        <div class="row">
            <div class="col">
                <a href="{{url_for('main.book')}}"><button class="btn btn-outline btn-info">Book session</button></a>
                <h3>Booked sessions</h3>
                <table class="table table-hover table-dark">
                    <thead>
                        <tr>
                            <!-- Your Columns HERE -->
                            <th scope="col">TAREHE</th>
                            <th scope="col">SERVICE</th>
                            <th scope="col">EMAIL</th>
                            <th scope="col">STATUS</th>
                            <th scope="col">CANCEL BOOKING</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for session in session %}
                        <tr>
                            <td>{{session.tarehe}}</td>
                            <td>{{session.service}}</td>
                            <td>{{session.email}}</td>
                            <td>{{session.status}}</td>
                            <td><button><a href="{{url_for('main.del_posts', id=session.id)}}">Cancel</a></button></td>
                        </tr>
                        {% endfor%}
                    </tbody>
                    </table>
            </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h3>Cancelled sessions</h3>
                
                <table class="table table-hover table-dark">
                    <thead>
                        <tr>
                            <!-- Your Columns HERE -->
                            <th scope="col">TAREHE</th>
                            <th scope="col">SERVICE</th>
                            <th scope="col">EMAIL</th>
                            <th scope="col">STATUS</th>
                            <th scope="col">BOOK SERVICE</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for session in sessions %}
                        <tr>
                            <td>{{session.tarehe}}</td>
                            <td>{{session.service}}</td>
                            <td>{{session.email}}</td>
                            <td>{{session.status}}</td>
                            <td><a href="{{url_for('main.edit_session', id=session.id)}}"><button>Book service</button></a></td>
                        </tr>
                        {% endfor%}
                    </tbody>
                    </table>
            </div>
            <div class="col">
                <h2>Available Sessions</h2>
                    <div class="container-fluid">
        <div class="row">
            <div class="col">
                <table class="table table-hover table-dark">
                    <thead>
                        <tr>
                            <!-- Your Columns HERE -->
                            <th scope="col">TAREHE</th>
                            <th scope="col">SERVICE</th>
                            <th scope="col">EMAIL</th>
                            <th scope="col">STATUS</th>
                            <th scope="col">BOOK SERVICE</th>

                        </tr>
                    </thead>
                    <tbody>
                        {% for session in available %}
                        <tr>
                            <td>{{session.tarehe}}</td>
                            <td>{{session.service}}</td>
                            <td>{{session.email}}</td>
                            <td>{{session.status}}</td>
                            <td><a href="{{url_for('main.edit_available', id=session.id)}}"><button>Book service</button></a></td>     
                        </tr>
                        {% endfor%}
                    </tbody>
                    </table>
            </div>
        </div>
    </div>

{%endblock%}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation" id="navbar" style="color: #602323;"> 
    <div class="container-fluid ">
        <div class="navbar-header ">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"></a>
            <a class="navbar-brand" href=""> </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav " >
                <li style="height: 80px; font-size: 50px; font-weight: 600;"><span style="color: red;">Smar</span><span style="color: cyan;">Time</span></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">

                <li><a id="navi" href="/">Home</a></li>
                <li>
                    <a id="navi" href="/homepage">Bookings</a>
                </li>
                <li>
                    <a id="navi" href="/login">Log In</a>
                </li>
                <li>
                    <a id="navi" href="/register">Register</a>
                </li>
                <li>
                    <a id="navi" href="{{url_for('auth.logout')}}">Logout</a>
                </li>

            </ul>
        </div>

    </div>
</div>